spring:
  application:
    name: async-executor

log:
  path: /usr/local/tomcat/logs/executor
  max:
    history: 7
    filesize: 20

server:
  port: 8012
#  profiles:
#    active: test


management:
  port: 8012
  security:
    enabled: true


logging:
  config: classpath:logback-spring.xml

queue:
  config:
    threadCount: 100

executor:
  server:
    center:
      host: http://localhost:20790
  client:
    port: 20788
    serviceId: async-excutor


